name: Build Noctalia Package

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialize pacman
        run: |
          pacman-key --init
          pacman-key --populate archlinux

      - name: Install Build Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm \
            base-devel \
            pacman-contrib \
            git \
            gcc \
            meson \
            ninja \
            wayland \
            wayland-protocols \
            libglvnd \
            freetype2 \
            fontconfig \
            cairo \
            pango \
            harfbuzz \
            libxkbcommon \
            glib2 \
            libsecret \
            libsodium \
            sdbus-cpp \
            pipewire \
            wireplumber \
            polkit \
            pam \
            curl \
            libwebp \
            libjxl \
            libsndfile \
            librsvg \
            libqalculate \
            libxml2 \
            md4c \
            tomlplusplus \
            libical \
            nlohmann-json \
            stb \
            jemalloc

      - name: Create Builder User
        run: |
          useradd -m builder
          chown -R builder:builder "$GITHUB_WORKSPACE"

      - name: Build Package
        run: |
          su builder -c "
            cd $GITHUB_WORKSPACE/noctalia-git &&
            makepkg -fc --noconfirm
          "

      - name: Create Repository
        run: |
          mkdir -p deploy/repo/x86_64

          cp noctalia-git/*.pkg.tar.zst deploy/repo/x86_64/

          repo-add \
            deploy/repo/x86_64/gnuslashlinux.db.tar.gz \
            deploy/repo/x86_64/*.pkg.tar.zst

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: deploy
